name: Deploy Application (Lambda + Frontend)

on:
  push:
    branches: [main]
    paths:
      - 'lamnbda/**'
      - 'frontend/**'
  workflow_run:
    workflows: ["Terraform Infrastructure"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-app:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code from triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Verify directory structure
        run: |
          echo "Root contents:"
          ls -l
          echo "Lambda folder:"
          ls -l lambda
          echo "Frontend folder:"
          ls -l frontend

      - name: Generate config.json from Terraform output
        run: |
          cd terraform
          terraform init -input=false \
            -backend-config="bucket=willofleming-terraform-state" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-locks"

          API_URL=$(terraform output -raw api_gateway_url)
          echo "✅ API_URL from Terraform: $API_URL"

          echo "{\"apiBaseUrl\": \"$API_URL\"}" > ../frontend/config.json
          echo "✅ config.json contents:"
          cat ../frontend/config.json

      - name: Final check before deploy
        run: |
          echo "Checking files before S3 sync:"
          find frontend
          test -f frontend/index.html || { echo "❌ index.html missing"; exit 1; }
          test -f frontend/script.js || { echo "❌ script.js missing"; exit 1; }
          test -f frontend/config.json || { echo "❌ config.json missing"; exit 1; }

      - name: Deploy frontend to S3
        run: |
          set -e
          echo "Frontend folder contents:"
          ls -l frontend
          echo "config.json:"
          cat frontend/config.json || { echo "❌ config.json missing"; exit 1; }
          aws s3 sync frontend/ s3://willofleming-event-announcement-bucket/ --delete --debug

